import type { StubPageConfig } from '@/lib/stub-page';

const defaultMessage =
  'Cette rubrique sera publiée prochainement par le secrétariat du Royaume de Bapa et les partenaires institutionnels.';

export const stubPagesByPath: Record<string, StubPageConfig> = {
  'royaume/traditions': {
    title: 'Le Royaume',
    heading: 'Traditions',
    label: 'Le Royaume',
    description: 'Rites, cérémonies et coutumes du Royaume de Bapa.',
    intro: 'Masques, danses royales et calendrier des fêtes traditionnelles du village.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Le Royaume', href: '/royaume/mot-du-roi' },
      { label: 'Traditions' },
    ],
    footerLinks: [
      { href: '/royaume/langues-et-cultures', label: 'Langues et Cultures' },
      { href: '/', label: 'Accueil' },
    ],
  },
  'developpement/adevipa/sante': {
    title: 'Développement',
    heading: 'Santé',
    label: 'ADEVIPA',
    description: 'Actions ADEVIPA en santé communautaire à Bapa.',
    intro: 'Campagnes de santé, prévention et équipements au service des familles du village.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'ADEVIPA', href: '/developpement/adevipa' },
      { label: 'Santé' },
    ],
    footerLinks: [
      { href: '/developpement/adevipa/education', label: 'Éducation' },
      { href: '/developpement/adevipa', label: '← ADEVIPA' },
    ],
  },
  'developpement/adevipa/education': {
    title: 'Développement',
    heading: 'Éducation',
    label: 'ADEVIPA',
    description: 'Actions ADEVIPA en éducation et formation à Bapa.',
    intro: 'Infrastructures scolaires, soutien aux élèves et accompagnement des jeunes générations.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'ADEVIPA', href: '/developpement/adevipa' },
      { label: 'Éducation' },
    ],
    footerLinks: [
      { href: '/developpement/adevipa/sante', label: 'Santé' },
      { href: '/developpement/adevipa', label: '← ADEVIPA' },
    ],
  },
  'developpement/rock-futura': {
    title: 'Développement',
    heading: 'Rock Futura Finance',
    label: 'Projets',
    description: 'Initiative Rock Futura Finance pour le développement local.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Rock Futura Finance' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Tous les projets' }],
  },
  'developpement/forum-h2050': {
    title: 'Développement',
    heading: 'Forum Bapa H2050',
    label: 'Projets',
    description: 'Vision prospective du Bapa de demain jusqu’à l’horizon 2050.',
    intro: 'Stratégie, concertation et feuille de route pour les générations futures.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Forum Bapa H2050' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Tous les projets' }],
  },
  'developpement/bapa-connect': {
    title: 'Développement',
    heading: 'Bapa Connect',
    label: 'Projets',
    description: 'Relier la diaspora et la communauté locale par le numérique.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Bapa Connect' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Tous les projets' }],
  },
  'developpement/grassfield': {
    title: 'Développement',
    heading: 'Grassfield Research Institute',
    label: 'Projets',
    description: 'Recherche et action pour l’eau, l’électricité et l’environnement.',
    intro: 'Réseaux vitaux et protection des Grassfields au service du village.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Grassfield Research Institute' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Tous les projets' }],
  },
  'developpement/grassfield/programme': {
    title: 'Développement',
    heading: 'Gestion environnement',
    label: 'Développement',
    description: 'Gestion et protection de l’environnement et des sources naturelles.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Gestion environnement' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Développement' }],
  },
  'developpement/grassfield/electricite': {
    title: 'Développement',
    heading: 'Réseau électrique',
    label: 'Développement',
    description: 'Développement du réseau électrique communautaire à Bapa.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Réseau électrique' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Développement' }],
  },
  'developpement/grassfield/eau': {
    title: 'Développement',
    heading: "Accès à l'eau",
    label: 'Développement',
    description: "Amélioration de l'accès à l'eau potable dans le Royaume de Bapa.",
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: "Accès à l'eau" },
    ],
    footerLinks: [{ href: '/developpement', label: '← Développement' }],
  },
  'developpement/cremepa': {
    title: 'Développement',
    heading: 'CREMEPA',
    label: 'Développement',
    description: 'CREMEPA au service de la cohésion et du développement local à Bapa.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'CREMEPA' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Développement' }],
  },
  'developpement/ajeepa': {
    title: 'Développement',
    heading: 'AJEEPA',
    label: 'Développement',
    description: 'AJEEPA — association et initiatives au service du village de Bapa.',
    intro: 'Programmes, actions et partenariats portés par AJEEPA (contenu à compléter).',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'AJEEPA' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Développement' }],
  },
  'tourisme/introductionenjeux': {
    title: 'Tourisme',
    heading: 'Enjeux',
    label: 'Tourisme',
    description: 'Tourisme culturel et patrimonial au Royaume de Bapa.',
    intro: 'Enjeux, opportunités et stratégie de mise en valeur du Royaume de Bapa.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Tourisme', href: '/tourisme/introductionenjeux' },
      { label: 'Enjeux' },
    ],
    footerLinks: [
      { href: '/tourisme/visitez-bapa', label: 'Visitez Bapa' },
      { href: '/tourisme/musee', label: 'Musée Case Patrimoniale' },
      { href: '/tourisme/restaurant', label: 'Les Saveurs du Palais' },
      { href: '/', label: '← Accueil' },
    ],
  },
  'tourisme/organisation': {
    title: 'Tourisme',
    heading: 'Organisation et promotion',
    label: 'Tourisme',
    description: 'Organisation touristique et promotion du Royaume de Bapa.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Tourisme', href: '/tourisme/introductionenjeux' },
      { label: 'Organisation et promotion' },
    ],
    footerLinks: [{ href: '/tourisme/introductionenjeux', label: '← Enjeux' }],
  },
  'tourisme/sites': {
    title: 'Tourisme',
    heading: 'Sites touristiques',
    label: 'Tourisme',
    description: 'Sites naturels et culturels à découvrir à Bapa.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Enjeux', href: '/tourisme/introductionenjeux' },
      { label: 'Sites touristiques' },
    ],
    footerLinks: [
      { href: '/tourisme/visitez-bapa', label: 'Carte — Visitez Bapa' },
      { href: '/tourisme/musee', label: 'Musée Case Patrimoniale' },
      { href: '/tourisme/introductionenjeux', label: '← Enjeux' },
    ],
  },
  mediatheque: {
    title: 'Médiathèque',
    heading: 'Médiathèque',
    label: 'Ressources',
    description:
      'Médiathèque du Royaume de Bapa : photos, documentation PDF, vidéos et audio classés par thème.',
    message: defaultMessage,
    breadcrumbs: [{ label: 'Accueil', href: '/' }, { label: 'Médiathèque' }],
    footerLinks: [{ href: '/echos', label: 'Échos de Bapa' }],
  },
  'communaute/roles': {
    title: 'Les Communautés',
    heading: 'Rôles de communautés',
    label: 'Les Communautés',
    description:
      'Rôles et missions des communautés du Royaume de Bapa : village, diaspora, institutions et groupes d’action.',
    intro:
      'Organisation des responsabilités au service du Royaume de Bapa, de la diaspora et des partenaires institutionnels.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Les Communautés', href: '/communaute' },
      { label: 'Rôles de communautés' },
    ],
    footerLinks: [
      { href: '/communaute/cameroun', label: 'Communauté au Cameroun' },
      { href: '/communaute', label: '← Les Communautés' },
    ],
  },
  'communaute/partenaires': {
    title: 'Les Communautés',
    heading: 'Partenaires',
    label: 'Les Communautés',
    description:
      'Partenaires du Royaume de Bapa par thème : institutionnel, entreprises, médias et associatif.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Les Communautés', href: '/communaute' },
      { label: 'Partenaires' },
    ],
    footerLinks: [{ href: '/communaute', label: '← Les Communautés' }],
  },
};
