import type { StubPageConfig } from '@/lib/stub-page';

const defaultMessage =
  'Cette rubrique sera publiée prochainement par le secrétariat du village royal et les partenaires institutionnels.';

export const stubPagesByPath: Record<string, StubPageConfig> = {
  'royaume/traditions': {
    title: 'Le Royaume',
    heading: 'Traditions',
    label: 'Le Royaume',
    description: 'Rites, cérémonies et coutumes du Royaume de Bapa.',
    intro: 'Masques, danses royales et calendrier des fêtes traditionnelles du village.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Le Royaume', href: '/royaume/mot-du-roi' },
      { label: 'Traditions' },
    ],
    footerLinks: [
      { href: '/royaume/langues-et-cultures', label: 'Langues et Cultures' },
      { href: '/', label: 'Accueil' },
    ],
  },
  'developpement/adevipa/sante': {
    title: 'Développement',
    heading: 'Santé et éducation',
    label: 'ADEVIPA',
    description: 'Actions ADEVIPA en santé communautaire et éducation à Bapa.',
    intro: 'Campagnes de santé, équipements scolaires et accompagnement des jeunes.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'ADEVIPA', href: '/developpement/adevipa' },
      { label: 'Santé et éducation' },
    ],
    footerLinks: [{ href: '/developpement/adevipa', label: '← ADEVIPA' }],
  },
  'developpement/rock-futura': {
    title: 'Développement',
    heading: 'Rock Futura Finance',
    label: 'Projets',
    description: 'Initiative Rock Futura Finance pour le développement local.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Rock Futura Finance' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Tous les projets' }],
  },
  'developpement/forum-h2050': {
    title: 'Développement',
    heading: 'Forum Bapa H2050',
    label: 'Projets',
    description: 'Vision prospective du Bapa de demain jusqu’à l’horizon 2050.',
    intro: 'Stratégie, concertation et feuille de route pour les générations futures.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Forum Bapa H2050' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Tous les projets' }],
  },
  'developpement/bapa-connect': {
    title: 'Développement',
    heading: 'Bapa Connect',
    label: 'Projets',
    description: 'Relier la diaspora et la communauté locale par le numérique.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Bapa Connect' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Tous les projets' }],
  },
  'developpement/grassfield': {
    title: 'Développement',
    heading: 'Grassfield Research',
    label: 'Projets',
    description: 'Recherche et action pour l’eau, l’électricité et l’environnement.',
    intro: 'Réseaux vitaux et protection des Grassfields au service du village.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Grassfield Research' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Tous les projets' }],
  },
  'developpement/grassfield/programme': {
    title: 'Développement',
    heading: 'Programme environnemental',
    label: 'Grassfield Research',
    description: 'Programme de protection de l’environnement et des sources naturelles.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Grassfield Research', href: '/developpement/grassfield' },
      { label: 'Programme env.' },
    ],
    footerLinks: [{ href: '/developpement/grassfield', label: '← Grassfield' }],
  },
  'developpement/grassfield/electricite': {
    title: 'Développement',
    heading: 'Réseau électrique',
    label: 'Grassfield Research',
    description: 'Développement du réseau électrique communautaire à Bapa.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Grassfield Research', href: '/developpement/grassfield' },
      { label: 'Réseau électrique' },
    ],
    footerLinks: [{ href: '/developpement/grassfield', label: '← Grassfield' }],
  },
  'developpement/grassfield/eau': {
    title: 'Développement',
    heading: "Accès à l'eau",
    label: 'Grassfield Research',
    description: "Amélioration de l'accès à l'eau potable dans le village royal.",
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Grassfield Research', href: '/developpement/grassfield' },
      { label: "Accès à l'eau" },
    ],
    footerLinks: [{ href: '/developpement/grassfield', label: '← Grassfield' }],
  },
  'developpement/cremepa': {
    title: 'Développement',
    heading: 'Cremepa',
    label: 'Projets',
    description: 'Projet Cremepa au service de la cohésion et du développement local.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Développement', href: '/developpement' },
      { label: 'Cremepa' },
    ],
    footerLinks: [{ href: '/developpement', label: '← Tous les projets' }],
  },
  'economie/tourisme': {
    title: 'Tourisme',
    heading: 'Introduction et enjeux',
    label: 'Économie & tourisme',
    description: 'Tourisme culturel et patrimonial au Royaume de Bapa.',
    intro: 'Enjeux, opportunités et stratégie de mise en valeur du village royal.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Tourisme', href: '/economie/tourisme' },
      { label: 'Introduction' },
    ],
    footerLinks: [
      { href: '/tourisme/musee', label: 'Musée Case Patrimoniale' },
      { href: '/', label: 'Accueil' },
    ],
  },
  'economie/tourisme/organisation': {
    title: 'Tourisme',
    heading: 'Organisation et promotion',
    label: 'Économie & tourisme',
    description: 'Organisation touristique et promotion du village de Bapa.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Tourisme', href: '/economie/tourisme' },
      { label: 'Organisation' },
    ],
    footerLinks: [{ href: '/economie/tourisme', label: '← Introduction' }],
  },
  'economie/tourisme/restaurant': {
    title: 'Tourisme',
    heading: 'Restaurant Patrimoniale',
    label: 'Économie & tourisme',
    description: 'Le restaurant patrimonial du village royal de Bapa.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Tourisme', href: '/economie/tourisme' },
      { label: 'Restaurant' },
    ],
    footerLinks: [{ href: '/tourisme/musee', label: 'Musée' }],
  },
  'economie/tourisme/sites': {
    title: 'Tourisme',
    heading: 'Sites touristiques',
    label: 'Économie & tourisme',
    description: 'Sites naturels et culturels à découvrir à Bapa.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'Tourisme', href: '/economie/tourisme' },
      { label: 'Sites touristiques' },
    ],
    footerLinks: [{ href: '/#visitez-bapa', label: 'Visitez Bapa' }],
  },
  mediatheque: {
    title: 'Médiathèque',
    heading: 'Médiathèque',
    label: 'Ressources',
    description: 'Archives photo, vidéo et documents officiels du Royaume de Bapa.',
    message: defaultMessage,
    breadcrumbs: [{ label: 'Accueil', href: '/' }, { label: 'Médiathèque' }],
    footerLinks: [{ href: '/communaute/echos', label: 'Échos de Bapa' }],
  },
  'communaute/partenaires': {
    title: 'La Communauté',
    heading: 'Partenaires',
    label: 'Communauté',
    description: 'Partenaires institutionnels et associatifs du village royal.',
    message: defaultMessage,
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'La Communauté', href: '/communaute' },
      { label: 'Partenaires' },
    ],
    footerLinks: [{ href: '/communaute', label: '← Communauté' }],
  },
  'communaute/contacts': {
    title: 'La Communauté',
    heading: 'Contacts',
    label: 'Communauté',
    description: 'Coordonnées et formulaire de contact du secrétariat de Bapa.',
    message:
      'Les coordonnées officielles et le formulaire de contact seront publiés prochainement. En attendant, suivez les actualités dans les Échos.',
    breadcrumbs: [
      { label: 'Accueil', href: '/' },
      { label: 'La Communauté', href: '/communaute' },
      { label: 'Contacts' },
    ],
    footerLinks: [
      { href: '/communaute/echos', label: 'Échos de Bapa' },
      { href: '/communaute', label: '← Communauté' },
    ],
  },
};
